augmentation:
  brightness_range:
  - 0.8
  - 1.2
  height_shift_range: 0.1
  horizontal_flip: true
  rotation_range: 25
  width_shift_range: 0.1
  zoom_range: 0.2
image:
  color_mode: rgb
  size: !!python/tuple
  - 224
  - 224
num_classes: 13
training:
  batch_size: 32
