augmentation:
  train:
    brightness_range:
    - 0.8
    - 1.2
    fill_mode: nearest
    height_shift_range: 0.1
    horizontal_flip: true
    rotation_range: 25
    width_shift_range: 0.1
    zoom_range: 0.2
  validation_test:
    augmentation: none
    only_rescale: true
dataset:
  test_dir: Modeling/Crop Disease Dataset/test
  total_classes: 13
  train_dir: Modeling/Crop Disease Dataset/train
  train_samples: 74880
  valid_dir: Modeling/Crop Disease Dataset/valid
  valid_samples: 19804
generator:
  class_mode: categorical
  seed: 42
  shuffle:
    train: true
    validation: false
image:
  color_mode: rgb
  normalization: 1./255
  size: !!python/tuple
  - 224
  - 224
metadata:
  creation_date: '2026-01-27 16:40:49.269665'
  keras_version: 3.10.0
  tensorflow_version: 2.19.0
training:
  batch_size: 32
  steps_per_epoch: 2340
  validation_steps: 618
